# Generated by Django 3.0.8 on 2020-07-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.FloatField()),
                ('square_feet', models.IntegerField()),
                ('description', models.TextField()),
                ('agent', models.CharField(max_length=255)),
                ('contact', models.EmailField(max_length=255)),
            ],
        ),
    ]
