# Generated by Django 3.0.8 on 2020-07-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zemax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
