# Generated by Django 3.0.8 on 2020-07-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zemax', '0002_house_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='year',
            field=models.IntegerField(default=2020),
        ),
    ]
