# Generated by Django 3.0.8 on 2020-07-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zemax', '0003_house_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
