# Generated by Django 3.0.8 on 2020-07-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zemax', '0004_auto_20200704_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image2',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
