# Generated by Django 3.0.8 on 2020-07-06 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemax', '0008_auto_20200705_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='image2',
        ),
    ]
