# Generated by Django 3.0.8 on 2020-07-06 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zemax', '0009_remove_house_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image2',
            field=models.ImageField(blank=True, default='default.png', upload_to='house_pics'),
        ),
    ]
