# Generated by Django 3.0.8 on 2020-07-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zemax', '0012_auto_20200706_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image2',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='house_pics'),
        ),
    ]
