# Generated by Django 3.0.8 on 2020-07-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zemax', '0015_auto_20200706_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image3',
            field=models.ImageField(default='default.jpg', upload_to='house_pics'),
        ),
    ]
