# Generated by Django 3.0.8 on 2020-07-08 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zemax', '0017_auto_20200706_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image',
            field=models.CharField(blank=True, max_length=255, verbose_name='Image 1'),
        ),
        migrations.AlterField(
            model_name='house',
            name='image2',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='house_pics', verbose_name='Image 2'),
        ),
        migrations.AlterField(
            model_name='house',
            name='image3',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='house_pics', verbose_name='Image 3'),
        ),
    ]
