# Generated by Django 3.0.8 on 2020-07-08 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zemax', '0018_auto_20200707_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_picture', models.ImageField(blank=True, default='default.jpg', upload_to='house_pics', verbose_name='House Image')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zemax.House')),
            ],
        ),
    ]
