# Generated by Django 3.0.8 on 2020-07-14 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemax', '0019_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='image',
        ),
        migrations.RemoveField(
            model_name='house',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='house',
            name='image3',
        ),
    ]
