# Generated by Django 3.0.8 on 2020-07-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zemax', '0020_auto_20200713_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='house_image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='house_pics'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
