# Generated by Django 3.0.8 on 2020-07-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zemax', '0021_auto_20200713_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='house_image10',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='house_pics'),
        ),
        migrations.AddField(
            model_name='house',
            name='house_image11',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='house_pics'),
        ),
        migrations.AddField(
            model_name='house',
            name='house_image12',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='house_pics'),
        ),
        migrations.AddField(
            model_name='house',
            name='house_image13',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='house_pics'),
        ),
        migrations.AddField(
            model_name='house',
            name='house_image14',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='house_pics'),
        ),
        migrations.AddField(
            model_name='house',
            name='house_image15',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='house_pics'),
        ),
        migrations.AddField(
            model_name='house',
            name='house_image16',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='house_pics'),
        ),
        migrations.AddField(
            model_name='house',
            name='house_image17',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='house_pics'),
        ),
        migrations.AddField(
            model_name='house',
            name='house_image2',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='house_pics'),
        ),
        migrations.AddField(
            model_name='house',
            name='house_image3',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='house_pics'),
        ),
        migrations.AddField(
            model_name='house',
            name='house_image4',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='house_pics'),
        ),
        migrations.AddField(
            model_name='house',
            name='house_image5',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='house_pics'),
        ),
        migrations.AddField(
            model_name='house',
            name='house_image6',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='house_pics'),
        ),
        migrations.AddField(
            model_name='house',
            name='house_image7',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='house_pics'),
        ),
        migrations.AddField(
            model_name='house',
            name='house_image8',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='house_pics'),
        ),
        migrations.AddField(
            model_name='house',
            name='house_image9',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='house_pics'),
        ),
    ]
