# Generated by Django 3.0.8 on 2020-07-15 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zemax', '0023_auto_20200714_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='house_image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='house_pics'),
        ),
    ]
