# Generated by Django 3.0.8 on 2020-07-16 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemax', '0028_house_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='manager',
        ),
    ]
