# Generated by Django 3.0.8 on 2020-07-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zemax', '0029_remove_house_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='house_image',
            field=models.ImageField(blank=True, default='default.jpg', max_length=1500, upload_to='house_pics', verbose_name='House Image'),
        ),
    ]
